### ISSUE TITLE
DO Sync location

### ISSUE THREAD

**Issue by tomphilpotts** [bitkidd/DigitalOcean-Spaces-Sync#29]
Hi

I am having an issue setting the route to the spaces.

At the moment the current route is 'var/www/html/wp-content/uploads'

Where as the spaces is set up as:
wp-content > uploads > 2019 > *

We are not able to move the data because of the 32gb of images.

Plugin settings:
Full URL-path to files: http://domain.com/wp-content/uploads
Local: wp-content/uploads
Storage Prefix: wp-content/uploads

How would I set the correct path? 

Is there another way to configure the file_path or upload_url_path? 

Thanks

**Comment by brightidea** [comment]
Wondering same thing. Struggling to get this to work properly with proper pathing on a multisite install using docker. Keeps wanting to include the base server path ('var/www/html/') when uploading to the spaces.

**Comment by budgetsavvybride** [comment]
Is there any other way to get support for this issue other than Github? This has been affecting my website for several weeks. We have to manually move the images after any upload and our site is very image-heavy.

**Comment by zeidanbm** [comment]
@BoldAnchor I Had similar issue and went through the plugin code and it seems that it's not doing anything the `upload_url_path` that we provide. At some point the plugin needs to use the wordPress funciton `update_option` to change the `upload_url_path` but it's not.
To solve this for now I modified the database directly. Or you can login to the wordpress backend and then navigate to `/wp-admin/options.php` to modify the `upload_url_path` parameter. Once done it will be turned on under `Settings -> Media -> Full URL path to files` to verify that it worked.

If I want to save my attachments at DO inside wp-content > uploads > 2019 > *
and assuming I have my WordPress attachments uploads at /wp-content/uploads

Then I would do the following settings
Plugin settings:
upload_url_path: https://subdomain.example.com/wp-content/uploads
Local: /var/www/html/example.com/wp-content/uploads (I would use the full path on my server, depending on your server configuration)
Storage Prefix: /wp-content/uploads

The year part of the folder (2019) followed by the month will only happen if you have your `Settings -> Media -> Organize my uploads into month- and year-based folders` turned on.

**Comment by BoldAnchor** [comment]
Hey, 

I tried this but it did not work:

**Settings -> Media -> Full URL path to files - is already active.**
Store uploads in this folder: wp-content/uploads
Full URL path to files: https://sub.example.com/wp-content/uploads

**DO Plugin settings**
Full URL-path to files: https://sub.example.com/wp-content/uploads
Local path: wp-content/uploads
Storage prefix: wp-content/uploads
Filemask/Regex for ignored files: 'empty'

**To confirm on sync**
Presently this is what is happening (btw this was happening because I had a cron job running a shell script to sync local and DO-space)

On upload with the plugin below is happening: 
DO-space> wp-content > uploads > var > www > main > 2019 > 10

Effect desired! 
DO-space: wp-content > uploads > 2019 > 10

**Comment by zeidanbm** [comment]
hmm not sure why would this happen! the plugin uses the upload_path to figure out the DO path.
`$path = $upload_dir['basedir'] . DIRECTORY_SEPARATOR . $metadata['file'];`
I would go to /wp-admin/options.php and check the **upload_path** if it's set correctly, defaults to **wp-content/uploads**
Because the part `$upload_dir['basedir']` is determined by WordPress function `wp_upload_dir` which  is read from the upload_path.
PS: You can even set the upload_url_path with wordpress constant WP_CONTENT_URL in your wp-config.php file. Have not tried this but it says [in the docs](https://developer.wordpress.org/reference/functions/wp_upload_dir/#description).
